export const predefinedLocations: string[] = [
  'Ambato, Ecuador',
  'Babahoyo, Ecuador',
  'Chone, Ecuador',
  'Cuenca, Ecuador',
  'Daule, Ecuador',
  'Durán, Ecuador',
  'El Carmen, Ecuador',
  'Esmeraldas, Ecuador',
  'Guayaquil, Ecuador',
  'Huaquillas, Ecuador',
  'Ibarra, Ecuador',
  'Jipijapa, Ecuador',
  'La Libertad, Ecuador',
  'Latacunga, Ecuador',
  'Loja, Ecuador',
  'Machala, Ecuador',
  'Manta, Ecuador',
  'Milagro, Ecuador',
  'Montecristi, Ecuador',
  'Nueva Loja, Ecuador',
  'Pasaje, Ecuador',
  'Pedro Carbo, Ecuador',
  'Portoviejo, Ecuador',
  'Puerto Francisco de Orellana, Ecuador',
  'Quevedo, Ecuador',
  'Quito, Ecuador',
  'Remoto',
  'Riobamba, Ecuador',
  'Samborondón, Ecuador',
  'Sana Rosa, Ecuador',
  'Sangolquí, Ecuador',
  'Santa Elena, Ecuador',
  'Santo Domingo, Ecuador',
  'Tulcán, Ecuador',
];
